interfaces:
  spine1:
    loopback: "20.0.1.1"
    int_unnumbered: ["swp1", "swp2"]
  spine2:
    loopback: "20.0.1.2"
    int_unnumbered: ["swp1", "swp2"]
  leaf1:
    loopback: "20.0.1.3"
    int_unnumbered: ["swp1", "swp2"]
  leaf2:
    loopback: "20.0.1.4"
    int_unnumbered: ["swp1", "swp2"]

