interfaces:
  spine1:
    loopback: "20.0.1.1"
    int_unnumbered: ["swp1", "swp2"]
    int_nat: [ "swp3"]
  spine2:
    loopback: "20.0.1.2"
    int_unnumbered: ["swp1", "swp2"]
    int_nat: [ "swp3"]
  leaf1:
    loopback: "20.0.1.3"
    int_unnumbered: ["swp1", "swp2"]
    int_numbered: ["swp3"]
  leaf2:
    loopback: "20.0.1.4"
    int_unnumbered: ["swp1", "swp2"]
    int_numbered: ["swp3"]


subnets:
  leaf1: 
    network: [ "100.100.100.1/24"]
  leaf2: 
    network: [ "200.200.200.1/24"]
